I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/d6_d7_d8_d9.rpy", line 93, in script
    if choice == gfood_list[0] :
  File "game/d6_d7_d8_d9.rpy", line 93, in <module>
    if choice == gfood_list[0] :
NameError: name 'choice' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/d6_d7_d8_d9.rpy", line 93, in script
    if choice == gfood_list[0] :
  File "C:\Users\jena1\Desktop\RenPy\renpy-8.2.1-sdk\renpy\ast.py", line 1842, in execute
    if renpy.python.py_eval(condition):
  File "C:\Users\jena1\Desktop\RenPy\renpy-8.2.1-sdk\renpy\python.py", line 1209, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\jena1\Desktop\RenPy\renpy-8.2.1-sdk\renpy\python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/d6_d7_d8_d9.rpy", line 93, in <module>
    if choice == gfood_list[0] :
NameError: name 'choice' is not defined

Windows-10-10.0.22631 AMD64
Ren'Py 8.2.1.24030407
casanoba project 1.0
Fri Jun 21 16:44:45 2024
